infrastructure/main.tf
infrastructure/outputs.tf
infrastructure/preview.tfvars

N/A
At the moment, no vault is setup for preview environment; as such preview build fails.
This makes preview deployments use the existing AAT vault.
```
[ ] Yes
[x] No
```

Setup vault for preview

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDM-2268
Reduce number of instances from 2 to 1 for all envs apart from `demo`, `prod`, `aat` and `sprod`.
```
[ ] Yes
[x] No
```

RDM-2268: Reduce default capacity

---

dependency-check-suppressions.xml

We don't use Spring Framework 5.0.5.RELEASE + Spring Security (any
version)
https://tools.hmcts.net/jira/browse/RDM-2464
```
[ ] Yes
[X] No
```

[SKIP-PREVIEW] Suppress CVE-2018-1258 impacted products are not used

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-3002
This is pulled in by liquibase for JDBC driver support.  We don't use h2
in development or production.
```
[ ] Yes
[x] No
```

Suppress CVE-2018-14335 for h2database

---

src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java
src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java
src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java

Ensure that the user ID is used as is, and is not converted to lowercase.
https://tools.hmcts.net/jira/browse/RDM-2934.
Pass the user ID as is, when searching for a User Profile entity. Although not normally expected, this will allow User Profiles that have been created with a mixed-case email address to be accessed.
```
[ ] Yes
[x] No
```

[PREVIEW] RDM-2934: Use exact match on ID for retrieving User Profiles

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-2605
This app has no checkstyle issues at all.  So we're just bumping the
checkstyle tester.
```
[ ] Yes
[x] No
```

Bump checkstyle version to 8.12

---

build.gradle
dependency-check-suppressions.xml

- We don't manage the PG installation
- The version on Azure that we use is not impacted
https://tools.hmcts.net/jira/browse/RDM-3175
```
[ ] Yes
[x] No
```

CVE: suppress CVE-2016-7048

---

hub.Dockerfile

n/a
Fix version of Gradle to 4.10 to allow docker images to build
```
[ ] Yes
[x] No
```

fix gradle version in docker hub

---

dependency-check-suppressions.xml

Suppresses: CVE-2018-1000873, CVE-2018-14718, CVE-2018-14719,
CVE-2018-14720, CVE-2018-14721, CVE-2018-19360, CVE-2018-19361,
CVE-2018-19362
https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ ] No
```

Temporarily suppress jackson-databind CVEs

---

src/main/resources/db/changelog/db.changelog-RDM-3853.xml
src/main/resources/db/changelog/db.changelog-master.xml

N/A
According to RFC http://www.rfc-editor.org/errata_search.php?rfc=3696&eid=1690 email addresses can be up to 254 characters long. There's no justification for the current 64 characters limit.
```
[ ] Yes
[x] No
```

Increase email max length to 254

---

src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java
src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
src/test/resources/sql/create_user_profile.sql

https://tools.hmcts.net/jira/browse/RDM-4369.
Ensure the email address passed in the `uid` query parameter is decoded before use; requests from ccd-data-store-api will be sending this encoded.
```
[ ] Yes
[x] No
```

RDM-4369: Support reserved characters in userId email address

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-3551
Fixed CVE-2019-10072 by upgrading tomcat libraries. 
Other one CVE-2019-12814 jackson-databind has to suppress for now.  
```
[ ] Yes
[ x] No
```

Jackson databind cve error

---

charts/ccd-user-profile-api/Chart.yaml
charts/ccd-user-profile-api/requirements.yaml

bulk-scanning is currently blocked because of a clash in the tpl in an old version of chart-java, this was fixed in ~2.10

Bump java base chart

---

dependency-check-suppressions.xml

CCD-1331 (https://tools.hmcts.net/jira/browse/CCD-1331)
Updated CVE suppression dates in suppressions.xml file to 25/09/2021. Only remaining entry in this file is flagged as a false positive so no additional resolution work required.
```
[ ] Yes
[x] No
```

Updated CVE suppression dates to 25/09/2021

---

build.gradle
dependency-check-suppressions.xml

CCD-2108 (https://tools.hmcts.net/jira/browse/CCD-2108)
- Updated dependencyManagement section of build.gradle. Set version of org.apache.tomcat.embed group to 9.0.54 to resolve CVE-2021-42340.
- Removed suppression of CVE-2021-42340 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```

CCD-2108: Address CVE-2021-42340

---

build.gradle
dependency-check-suppressions.xml

CCD-2142 (https://tools.hmcts.net/jira/browse/CCD-2142)
- Updated build.gradle. Set value of override of spring-framework.version property to 5.3.12 to address CVE-2021-22096.
- Removed temporary suppression of CVE-2021-22096 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```

CCD-2142: Address CVE-2021-22096

---

dependency-check-suppressions.xml

CCD-2107 (https://tools.hmcts.net/jira/browse/CCD-2107)
Updated CVE suppression dates in dependency-check-suppressions.xml to 25/12/2021
```
[ ] Yes
[x] No
```

CCD-2107: Update CVE suppression dates

---

dependency-check-suppressions.xml

CCD-2231 (https://tools.hmcts.net/jira/browse/CCD-2231)
Changed CVE suppression dates in dependency-check-suppressions.xml to 2022-01-25.
```
[ ] Yes
[x] No
```

CCD-2231: Updated CVE suppression dates

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3109
Updated spring-framework.version to 5.3.19 and removed suppression for CVE-2022-22968
```
[ ] Yes
[X] No
```

CCD-3109 Updated spring-framework.version to 5.3.19 and removed suppression for CVE-2022-22968

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3264
Upgrading tomcat version to 10.0.21.
The documentation of Apache Tomcat 10.1.0-M1 to 10.1.0-M14, 10.0.0-M1 to 10.0.20, 9.0.13 to 9.0.62 and 8.5.38 to 8.5.78 for the EncryptInterceptor incorrectly stated it enabled Tomcat clustering to run over an untrusted network. This was not correct. While the EncryptInterceptor does provide confidentiality and integrity protection, it does not protect against all risks associated with running over any untrusted network, particularly DoS risks.
```
[ ] Yes
[ X] No
```

CVE-2022-29885: ccd-user-profile-api fix

---

dependency-check-suppressions.xml

CCD-3088 Remove redundant entries from suppression files - CVE-2020-36518 removed
https://tools.hmcts.net/jira/browse/CCD-3088
```
[ ] Yes
[ x] No
```

CCD-3088 Remove redundant entries from suppression files

---

build.gradle

CCD-3297 (https://tools.hmcts.net/jira/browse/CCD-3297)
Added junit formatter plugin to doLast section of smoke and functional test tasks.  This causes test result XML files to be created in the locations expected by the smoke and functional stages of the pipeline.  These locations were recently corrected under DTSPO-6817.
```
[ ] Yes
[x] No
```

CCD-3297: Added junit formatter to smoke and functional test tasks

---

dependency-check-suppressions.xml

CCD-3606 (https://tools.hmcts.net/jira/browse/CCD-3606)
Updated suppressions file to temporarily suppress CVE-2022-31197.  Also tied up indentation of temporary suppressions section.
```
[ ] Yes
[x] No
```

CCD-3606: Temporarily suppress CVE-2022-31197

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3606
CCD-3606: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression
```
[ ] Yes
[X] No
```

CCD-3606: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3432
CVE-2022-34305 tomcat upgrade 9.0.65
```
[ ] Yes
[ x] No
```

CCD-3432 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4233
CVE-2022-45143 Upgrade Tomcat to 9.0.69, suppression removed
```
[ ] Yes
[ x] No
```

CCD-4233 CVE-2022-45143 Upgrade Tomcat to 9.0.69, suppression removed

---

build.gradle
charts/ccd-user-profile-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4398
Upgrade tomcat and commons-fileupload  to resolve CVE-2023-24998
```
[ ] Yes
[ x] No
```

CCD-4398 Upgrade dependencies to resolve CVE-2023-24998

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4739
CCD-4739 : Fix CVE-2023-20863 (bump version of springframework)
```
[ ] Yes
[X] No
```

CCD-4739 : Fix CVE-2023-20863 (bump version of springframework)

---

.github/renovate.json
Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CCD-4845
Renovate config is now mandatory in every repo extending default org level config without using enabledManagers.
```
[ ] Yes
[x] No
```

CCD-4845: renovate config

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4970
removed suppression, no useage of Gauva detected
```
[ ] Yes
[X] No
```

CCD-4970 : Fix CVE-2020-8908  

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4972
Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 10.1.13
```
[ ] Yes
[x ] No
```

Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 10.1.13

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5160
CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0
```
[ ] Yes
[ x] No
```

CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0

---

charts/ccd-user-profile-api/Chart.yaml

Current failures in pipelines due to java chart requiring an update from 5.0.0 to 5.2.0 
+ echo ' chart 5.0.0 is deprecated, please upgrade to at least 5.2.0'
chart 5.0.0 is deprecated, please upgrade to at least 5.2.0
+ exit 1
https://build.hmcts.net/view/CDM%20DEV/job/HMCTS_a_to_c/job/ccd-user-profile-api/job/PR-399/544/execution/node/238/log/

Bump java chart due to pipeline failures

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5076
CVE-2023-33202 : Fix org.bouncycastle vulnerable version
```
[ ] Yes
[ x] No
```

CVE-2023-33202 : Fix org.bouncycastle vulnerable version

---

build.gradle

Lombok and the owasp dependency checker are build tools that should not form part of the deployed application.

Remove unnecessary runtime dependencies

---

infrastructure/prod.tfvars
infrastructure/variables.tf

Upgrade prod db size
