.travis.yml, build.gradle
Rdm 1951 Introduce travis and bintray
```
[ ] Yes
[x] No
```
=> Rdm 1951 Introduce travis and bintray

README.md
RDM-1951 Add travis status message
```
[ ] Yes
[x] No
```
=> Try travis

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
N/A
Use `product` and `component` from Jenkinsfile
```
[ ] Yes
[x] No
```
=> Update CNP product/component

infrastructure/aat.tfvars
N/A
Use preprod config for AAT
```
[ ] Yes
[x] No
```
=> CNP: Use preprod config for AAT

build.gradle, dependency-check-suppressions.xml
RDM-2012
Review build to pass new pipeline defintion
```
[x] Yes
[ ] No
```
=> RDM-2012 passing pipeline

Jenkinsfile_parameterized
=> use infrastructure

build.gradle, src/aat/java/uk/gov/hmcts/ccd/userprofile/tests/helper/S2SHelper.java
Figured out how to do it properly
=> Remove the temp hack on s2s-api

Jenkinsfile_parameterized
Only deploy to saat or sprod, nayab was accidentally deploying to sandbox before
```
[ ] Yes
[ ] No
```
=> Remove unneeded options

.travis.yml, Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
=> Add missing secrets

infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Disabled NL DB
Enable UK DB
```
[ ] Yes
[x] No
```
=> Switch on UK DB in AAT

dependency-check-suppressions.xml
=> Added CVE 2018 10054

infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
:warning: To be merged as part of release https://tools.hmcts.net/confluence/display/RSTR/CHG0032439+-+CCD+db+Migration+to+UK
```
[x] Yes
[ ] No
```
=> Do not merge: RDM-2173: Switch prod DB to UK South

.travis.yml, README.md
RDM-2250
Add codecov to README.md
```
[ ] Yes
[x] No
```
=> Add codecov to README.md

build.gradle, gradle/wrapper/gradle-wrapper.properties
RDM-2250
Update grade version and incorporate pmd
```
[ ] Yes
[x] No
```
=> Update gradle and use pmd based on codecov reports

README.md
=> Use the same convention as in the other two ccd java projects

infrastructure/demo.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Switch demo DBs to UK South
```
[ ] Yes
[x] No
```
=> Switch demo DBs to UK South

infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Switch SAAT DB to UK South
```
[ ] Yes
[x] No
```
=> Switch SAAT DB to UK South

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-2326
One more item in cve suppressions
```
[ ] Yes
[x] No
```
=> [SKIP-PREVIEW] Add one more item to suppress list

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2287
Removes the use_uk_db from infrastructure. Now that we've moved to UK, cleanup the code to allow the switch. WIP so we can wait until things are 100% confirmed and migrated.
```
[ ] Yes
[X] No
```
=> RDM-2287: remove use uk

infrastructure/main.tf, infrastructure/variables.tf
Implement the pattern outline in https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-TerraformConfiguration
Fixes: https://tools.hmcts.net/jira/browse/RDM-2387
```
[ ] Yes
[X] No
```
=> RDM-2387 moj-module-(postgres|webapp) use common_tags

Jenkinsfile_parameterized
Added ability to deploy on sandbox
```
[ ] Yes
[x ] No
```
=> add_deploy_to_sandbox

.travis.yml
https://tools.hmcts.net/jira/browse/RDM-2288
We don't need sudo and irt wastes setup time, also various cleanups and
cache as recommended
```
[ ] Yes
[ ] No
```
=> Sudoless Travis

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2625
1. Move local Azure keyvault to shared keyvault
2. Point all existing keys to shared
3. (No other vault keys present)
=> [PREVIEW] Vault: prep shared vault and copy keys (step 2)

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2625
Old vault is required while transition secrets from old to new vault
```
[ ] Yes
[x] No
```
=> [PREVIEW] RDM-2625: Fix - Reinstate old vault

infrastructure/main.tf
Vault cannot be reverted as it's failing while refreshing the state of a dependent secret.
=> Revert "[PREVIEW] RDM-2625: Fix - Reinstate old vault"

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDM-2311
```
[ ] Yes
[ ] No
```
=> Add basic nightly Jenkins build

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDM-2311
=> Nightly Jenkins builds: reset daily build time

README.md, infrastructure/variables.tf, src/main/resources/application.properties
None.
Minor config changes to allow the Case Admin Web application (with ID `ccd_admin`) to access the User Profile API.
```
[ ] Yes
[x] No
```
=> Allow Case Admin Web application (ccd_admin) access to User Profile API

src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileController.java, src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
https://tools.hmcts.net/jira/browse/RDM-2418
Clone REST endpoint for `PUT` operation and map to the `/users` path.
```
[ ] Yes
[x] No
```
=> RDM-2418: Map existing "update" operation to new endpoint

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2484
Whole shebang.  Need to check what happens when we remove that copied
key.  I think we might just need to bang it in recopy the key if it gets
deleted by TF.
```
[ ] Yes
[x] No
```
=> [PREVIEW] Use Azure vault

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484
```
[ ] Yes
[x] No
```
=> [PREVIEW] Remove Hashi vault

config/checkstyle/checkstyle.xml
https://tools.hmcts.net/jira/browse/RDM-2604
```
[ ] Yes
[x] No
```
=> Checkstyle: error on import check failures

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2635
Fix aat and prod to current per app ASP.  So making sure that is
correct, before adding shared ASP.
```
[ ] Yes
[x] No
```
=> [PREVIEW] Shared App Service Plan

Jenkinsfile_CNP, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/RDM-2947
Push build failures to seperate channels depending on the branch, PR or
environment.
```
[ ] Yes
[x] No
```
=> Surface build failures to slack

Dockerfile, hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-2687
```
[ ] Yes
[x] No
```
=> Docker: use cnp-java-base image

config/checkstyle/checkstyle.xml
https://tools.hmcts.net/jira/browse/RDM-2612
```
[ ] Yes
[x] No
```
=> Checkstyle ModifierOrder and NewlineAtEndOfFile fixes

src/main/resources/db/changelog/db.changelog-RDM-2761-UserProfileAuditTable.xml, src/main/resources/db/changelog/db.changelog-master.xml
RDM-2761
Add User Profile Audit Table
```
[ ] Yes
[x] No
```
=> [PREVIEW] RDM-2761 Add User Profile Audit Table

dependency-check-suppressions.xml
RDM-3549
Suppress warnings from slf4j:slf4j:1.7.25
```
[x] Yes
[ ] No
```
=> RDM-3549 Suppress warnings from slf4j:slf4j:1.7.25

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3592
```
[ ] Yes
[ ] No
```
=> Lock Terratform AzureRM to 1.19.0

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, infrastructure/outputs.tf
https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```
=> [PREVIEW] Use s2s vault

build.gradle, src/main/java/uk/gov/hmcts/ccd/data/userprofile/AuditAction.java, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntityRepository.java, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java, src/main/java/uk/gov/hmcts/ccd/domain/service/CreateUserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/DeleteUserProfileJurisdictionOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/FindAllUserProfilesOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileController.java, src/main/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpoint.java, src/main/java/uk/gov/hmcts/ccd/repository/PostgreSQLEnumType.java, src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java, src/test/java/uk/gov/hmcts/ccd/domain/service/DeleteUserProfileJurisdictionOperationTest.java, src/test/java/uk/gov/hmcts/ccd/domain/service/FindAllUserProfilesOperationTest.java, src/test/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperationTest.java, src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java, src/test/resources/sql/create_jurisdiction.sql, src/test/resources/sql/init_db.sql
RDM 2425
Audits on User Profile Operations
Supersedes #111 
```
[x] Yes
[ ] No
```
=> Rdm 2425 Audits on User Profile Operations

infrastructure/demo.tfvars
https://tools.hmcts.net/jira/browse/RDM-3765
```
[ ] Yes
[ ] No
```
=> Use per app ASP for demo

build.gradle
This addresses CVEs in jackson-databind
https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ ] No
```
=> Spring boot upgrade to v2.0.8

.travis.yml, README.md
Remove last remnants of Oracle JDK from README and Travis
https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ ] No
```
=> Use OpenJDK everywhere

Dockerfile, Jenkinsfile_CNP, charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/requirements.lock, charts/ccd-user-profile-api/requirements.yaml, charts/ccd-user-profile-api/values.aat.template.yaml, charts/ccd-user-profile-api/values.template.yaml, docker-compose.yml
https://tools.hmcts.net/jira/browse/RDM-3398
```
[ ] Yes
[ ] No
```
=> Implement Helm charts

charts/ccd-user-profile-api/values.template.yaml
Enable DB migration by default in Helm. Proper prod like deployment
needs something in pipeline to manage the DB migration.
https://tools.hmcts.net/jira/browse/RDM-3398
```
[ ] Yes
[ ] No
```
=> Migrate database in Helm

charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/requirements.yaml, charts/ccd-user-profile-api/values.aat.template.yaml, charts/ccd-user-profile-api/values.template.yaml
Remove alias for clarity and consistency with other charts.
https://tools.hmcts.net/jira/browse/RDM-3398
```
[ ] Yes
[ ] No
```
=> Cleanup: helm pod naming

build.gradle
https://tools.hmcts.net/jira/browse/RDM-3790
```
[ ] Yes
[ ] No
```
=> Bump use-latest-versions and ben-manes.versions

charts/ccd-user-profile-api/requirements.yaml
=> Update Java Helm chart

src/main/resources/application.properties
=> disable jpa logging

Dockerfile
https://tools.hmcts.net/jira/browse/RDM-4011
```
[ ] Yes
[ ] No
```
=> Use Kubernetes friendly Java image

build.gradle
https://tools.hmcts.net/jira/browse/RDM-4064
```
[ ] Yes
[ ] No
```
=> Bump Swagger2 from 2.9.0 to 2.9.2

build.gradle
https://tools.hmcts.net/jira/browse/RDM-4136
```
[ ] Yes
[ ] No
```
=> Upgrade pmd to 6.11.0 to address CVE-2019-7722

build.gradle, src/main/java/uk/gov/hmcts/ccd/auth/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/RPE-1005
Suppress coverage for very specific hibernate extension class,
It's hard to test
Very little value would be given in testing it
It doesn't currently have a test, and the only change to make sonar trigger on it was to fix a PMD violation
```
[ ] Yes
[ ] No
```
=> Suppress code coverage for library level class

infrastructure/main.tf, infrastructure/variables.tf, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-2618
* not on prod/aat
* We can't display the names yet
```
[ ] Yes
[x] No
```
=> [PREVIEW] Use shared App Insight

lib/AI-Agent.xml
=> Add classes for AppInsights

Dockerfile, hub.Dockerfile
Microsoft renamed the tag for consistency for the appinsights agent url, updated to new base image
```
[ ] Yes
[ ] No
```
=> Bump base image version

build.gradle
=> update Spring Boot version from v2.1.3 to v2.1.4

infrastructure/main.tf, infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/browse/RDM-4571
```
[ ] Yes
[ ] No
```
=> Deploy perftest env

infrastructure/ithc.tfvars
https://tools.hmcts.net/jira/browse/RDM-4694
```
[ ] Yes
[ ] No
```
=> added ithc terraform var file

Dockerfile
curl is not present in this docker image
```
[ ] Yes
[ ] No
```
=> Fix healthcheck

src/main/java/uk/gov/hmcts/ccd/domain/service/FindUserProfileOperation.java
=> removing no longer needed INFO logging

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-3551
```
[ ] Yes
[ x] No
```
=> RDM-3551 - upgraded owasp dependencycheck to 5.1.0

src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java, src/main/resources/db/changelog/db.changelog-RDM-5499.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java, src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
https://tools.hmcts.net/jira/browse/RDM-5499
handling duplicate / existing user scenario.
```
[ ] Yes
[x ] No
```
=> RDM-5499 - handling duplicate / existing user scenario.

charts/ccd-user-profile-api/values.template.yaml, infrastructure/variables.tf, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-5498
Please don't merge we're still waiting for the confirmation from RD / XUI regarding exact service name.
```
[ ] Yes
[ ] No
```
=> RDM-5498 - rd_professional_api as S2S authorised service.

dependency-check-suppressions.xml
Temporarily suppressing some new identified vulnerabilities. We already have the following ticket to sort that out for good: https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ x] No
```
=> fix failing build

build.gradle
=> removed appinsight 2.4.1 references

charts/ccd-user-profile-api/values.yaml
=> added identity

Jenkinsfile_CNP
Reverts hmcts/ccd-user-profile-api#213
=> Revert "disabled AAT aks deployment"

build.gradle, liquibase.gradle, src/main/java/uk/gov/hmcts/ccd/UserProfileApplication.java, src/test/java/uk/gov/hmcts/ccd/BaseTest.java, src/test/java/uk/gov/hmcts/ccd/data/TestConfiguration.java, src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java, src/test/resources/test.properties
Reverts hmcts/ccd-user-profile-api#217
New ticket created to address the issue. 
https://tools.hmcts.net/jira/browse/RDM-6706
=> Revert "Moving to hmcts version of liquibase which performs better DB locking"

build.gradle, charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/requirements.yaml, charts/ccd-user-profile-api/values.preview.template.yaml, dependency-check-suppressions.xml, web.config
https://tools.hmcts.net/jira/browse/RDM-5533
Disable `X-Powered-By` header
```
[ ] Yes
[x] No
```
=> RDM-5533 Disable X-Powered-By header

charts/ccd-user-profile-api/values.yaml
https://tools.hmcts.net/jira/browse/RDM-7098
add rd_professional_api to allowed services list for AKS
```
[ ] Yes
[X] No
```
=> add rd_professional_api to allowed services list

build.gradle, charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/values.yaml
https://tools.hmcts.net/jira/browse/RDM-7098
add rd_professional_api to allowed services list for AKS
```
[ ] Yes
[X] No
```
=> update chart version after allowed service list change

Jenkinsfile_CNP, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-7116
```
[ ] Yes
[x] No
```
=> RDM-7116-rm-ase-envir

dependency-check-suppressions.xml
This should be temp solution, tech debt ticket to investigate :https://tools.hmcts.net/jira/browse/RDM-7406 
```
[ ] Yes
[x] No
```
=> CVE suppress issue to unblock user-profile pipeline 

build.gradle, dependency-check-suppressions.xml
=> upgrade to befta fw 1.1.1

build.gradle, dependency-check-suppressions.xml, src/aat/java/uk/gov/hmcts/ccd/userprofile/tests/smoke/SmokeTest.java
https://tools.hmcts.net/jira/browse/RDM-7836
temporarily disable the smoke test lines in build.gradle file until a proper smoke test is introduced
```
[ ] Yes
[ X No
```
=> Build issue diagnosis

build.gradle, src/aat/resources/features/F-000/S-000.td.json
=> bump up dependency versions for cve remediation

build.gradle
=> RDM-7908-CVEs

src/aat/resources/features/F-097/F-097.feature
https://tools.hmcts.net/jira/browse/RDM-7986
Post-release cleanup.
```
[ ] Yes
[X] No
```
=> enable temporarily disabled tests

.github/workflows/swagger.yml
=> correct gradle task to call

.github/workflows/swagger.yml
https://tools.hmcts.net/jira/browse/RDM-7740
Establish automated publishing of swagger spec with a github workflow (fix applied)
```
[ ] Yes
[X] No
```
=> run on java 8, not 11

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/variables.tf
=> Terraform cleanup

infrastructure/outputs.tf
=> fixing tf output

dependency-check-suppressions.xml
=> temporary suppressions

build.gradle, dependency-check-suppressions.xml
RDM-8277: Resolve CVE's on ccd-user-profile-api Update Spring framwork
  [RDM-8277] (https://tools.hmcts.net/jira/browse/RDM-8277).
Resolve CVE's on ccd-user-profile-api Update Spring framwork
```
[x ] Yes
[ ] No
```
=> RDM-8277: Resolve CVE's on ccd-user-profile-api Update Spring framwork

Jenkinsfile_CNP, dependency-check-suppressions.xml
Fix develop pr so BEFTA tests work on other repositories
```
[ ] Yes
[ ] No
```
=> RDM-XXX Fix develop branch

build.gradle, dependency-check-suppressions.xml, src/aat/resources/features/F-097/F-097.feature
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-8625
Change description
Linked S-424 as smoke test
```
[ ] Yes
[x] No
```
=> Linked S-424 as smoke test

build.gradle
https://tools.hmcts.net/jira/browse/RDM-8796
Fix incomplete smoke test setup
```
[ ] Yes
[X] No
```
=> fix smoke tests

.travis.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/ccd/repository/PostgreSQLEnumType.java, src/test/java/uk/gov/hmcts/ccd/data/TestConfiguration.java
https://tools.hmcts.net/jira/browse/RDM-8788
Update project to Java 11 (including Gradle upgrade)
```
[ ] Yes
[x] No
```
=> RDM-8788 - Java 11 upgrade

Jenkinsfile_CNP, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9063
Publish smoke test results
```
[ ] Yes
[X] No
```
=> archive cucumber artefacts after smoke tests

.github/renovate.json, charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/requirements.yaml, dependency-check-suppressions.xml
=> Rdm 8784 helm renovate

build.gradle
=> upgrade to latest fw version

Jenkinsfile_CNP, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9467
```
[ ] Yes
[X] No
```
=> Adding a fix for CVE-2017-18640

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java
https://tools.hmcts.net/jira/browse/RDM-9478
```
[ ] Yes
[X] No
```
=> Fix All Temporarily Suppressed CVEs +develop

src/aat/resources/features/F-000/F-000.feature
https://tools.hmcts.net/jira/browse/RDM-9534
```
[ ] Yes
[X] No
```
=> Removing Health checks scenario as smoke tests

build.gradle, dependency-check-suppressions.xml
=> befta fw bump up

build.gradle
https://tools.hmcts.net/jira/browse/RDM-9115
Migrate UserProfile to use HMCTS Gradle Java Plugin
```
[ ] Yes
[x] No
```
=> Bump up hmcts plugin

src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java, src/main/resources/db/changelog/db.changelog-RDM-9052.xml, src/main/resources/db/changelog/db.changelog-master.xml
=> Rdm 9478 fix

dependency-check-suppressions.xml
=> temporarily suppress

build.gradle, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileAuditEntity.java
=> Revert UserProfileAuditEntity/liquibase changes

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, liquibase.gradle, src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestAutomationAdapter.java, src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java, src/aat/resources/features/F-000/S-000.td.json, src/aat/resources/features/F-097/S-504.td.json, src/main/java/uk/gov/hmcts/ccd/AliasWebConfig.java, src/main/java/uk/gov/hmcts/ccd/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/ccd/auth/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/ccd/endpoint/ReadinessHealthIndicator.java, src/main/resources/application.properties
Reverts hmcts/ccd-user-profile-api#337
=> Revert "Adding files for RDM-8934-test Data re execution"

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10294
Fix All Recent CVEs in All CCD Apps
```
[ ] Yes
[X] No
```
=> RDM-10294 Fix All Recent CVEs in All CCD Apps

dependency-check-suppressions.xml
=> temporary suppression

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10549
Fix CVEs Newly Reported on All 4 Java Apps
```
[ ] Yes
[X] No
```
=> RDM-10549 Fix CVEs Newly Reported on All 4 Java Apps

build.gradle, src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestAutomationAdapter.java, src/aat/java/uk/gov/hmcts/ccd/userprofile/befta/UserProfileTestDataLoader.java
https://tools.hmcts.net/jira/browse/RDM-10616
Bumped up befta-fw version to 6.3.0
```
[ ] Yes
[x] No
```
=> RDM-10616: Bump up befta-fw version to 6.3.0

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10808
fix newly reported CVE's in User Profile
```
[ ] Yes
[X] No
```
=> RDM-10808 fix newly reported CVE's in User Profile

src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-10196
Improve readiness checks
```
[X] Yes
[ ] No
```
=> RDM-10196 Improve readiness checks

build.gradle, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java, src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java, src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java, src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
https://tools.hmcts.net/jira/browse/RDM-7709
https://tools.hmcts.net/jira/browse/RDM-7707
User Profile: Fix a Bad request error in PUT /users/save endpoint
User Profile: Fix a Duplicate key bug in PUT /users endpoint
```
[ ] Yes
[X] No
```
=> Rdm 7709 7707

build.gradle, src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java, src/main/java/uk/gov/hmcts/ccd/domain/service/SaveUserProfileOperation.java, src/main/java/uk/gov/hmcts/ccd/domain/service/UserProfileOperation.java, src/test/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepositoryTest.java, src/test/java/uk/gov/hmcts/ccd/endpoint/userprofile/UserProfileEndpointIT.java
=> Rdm 7709 7707 PR

charts/ccd-user-profile-api/Chart.yaml
=> Bump chart number to resolve issue with broken build on develop branch

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11086
```
[ ] Yes
[X] No
```
=> RDM-11086 Upgrade to Postgres 11 on PerfTest

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11089
```
[ ] Yes
[X] No
```
=> RDM-11089 Upgrade to Postgres 11 on ITHC

build.gradle
https://tools.hmcts.net/jira/browse/RDM-11234
Upgrade Hikari CP Dependency in All CCD Apps
```
[ ] Yes
[X] No
```
=> RDM-11234 Upgrade Hikari CP Dependency in All CCD Apps

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11433
CVE-2021-22112 (User Profile)
```
[ ] Yes
[X] No
```
=> RDM-11433 CVE-2021-22112 (User Profile)

dependency-check-suppressions.xml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11089
```
[ ] Yes
[X] No
```
=> RDM-11089 Postgres11 upgrade clean-up

dependency-check-suppressions.xml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11086
```
[ ] Yes
[X] No
```
=> RDM-11086 Postgres11 upgrade clean-up

build.gradle
https://tools.hmcts.net/jira/browse/RDM-11507
CVE-2021-25122 (User Profile)
```
[ ] Yes
[X] No
```
=> RDM-11507 CVE-2021-25122 (User Profile)

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11765
Merge changes from master to develop
```
[ ] Yes
[X] No
```
=> Rdm 11765 develop

build.gradle
https://tools.hmcts.net/jira/browse/RDM-11729
```
[ ] Yes
[ ] No
```
=> RDM-11729: Upgrade Befta to 6.13.0

src/test/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandlerTest.java
=> RDM-9182: Add test

src/test/java/uk/gov/hmcts/ccd/endpoint/exception/RestExceptionHandlerTest.java
=> RDM-9182: Use Jupiter instead of standard JUnit annotation

build.gradle
=> RDM-9182: Exclude RestExceptionHandler from test coverage

build.gradle
=> RDM-11881 - Use jitpack for befta dependency

.github/workflows/scheduled-dummy-commit.yml
RDM-11603
```
[ ] Yes
[x] No
```
=> Update scheduled-dummy-commit.yml try force

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11957
```
[ ] Yes
[X] No
```
=> Upgrade to Postgres 11 

infrastructure/main.tf
=> Use correct product for postgres v11

src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-11957
```
[ ] Yes
[X] No
```
=> Upgrade to Postgres 11

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1230
CVE-2021-22112 (CCD User Profile API)
```
[ ] Yes
[x] No
```
=> CCD-1230 CVE-2021-22112 (CCD User Profile API)

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CCD-1131
integrate new pipeline stages for high level data setup
```
[ ] Yes
[x] No
```
=> Reduce auto-skip period to enable 2 uploads in master pipeline

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/CCD-1282
Jenkins library reference has been changed back to master branch from CCD-1131
```
[ ] Yes
[x] No
```
=> Changed Jenkins library reference back to master branch

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1268
CVE-2021-22118 in CCD User Profile API
```
[ ] Yes
[x] No
```
=> CCD-1268 CVE-2021-22118 in CCD User Profile API

charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/values.yaml, src/main/resources/application.properties, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/CCD-1268
CVE-2021-22118 in CCD User Profile API update configs
```
[ ] Yes
[x] No
```
=> CCD-1268 CVE-2021-22118 update config imports

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/CCD-1131
befta-fw update to 8.2.0
```
[ ] Yes
[x] No
```
=> befta-fw update to 8.2.0

Jenkinsfile_nightly
fix for enableDbMigration()
```
[ ] Yes
[x] No
```
=> fix for enableDbMigration()

build.gradle
https://tools.hmcts.net/jira/browse/CCD-1354
fix mutation test failure
```
[ ] Yes
[X] No
```
=> fix mutation test failure

dependency-check-suppressions.xml
Suppress CVE-2021-22119
```
[ ] Yes
[ ] No
```
=> Suppress CVE-2021-22119

src/main/java/uk/gov/hmcts/ccd/data/userprofile/UserProfileRepository.java, src/main/resources/db/migration/V20210727_1351__CCD-1351_add_index_userProfileId.sql
https://tools.hmcts.net/jira/browse/CCD-1351
Removed the additional user profile mapper invocation and added index for user_profile_id column
```
[ ] Yes
[x] No
```
=> CCD-1351: Improve performance of /profile endpoint to speed up CCD Logins

dependency-check-suppressions.xml
CCD-1993 (https://tools.hmcts.net/jira/browse/CCD-1993)
Updated CVE suppression dates in dependency-check-suppressions.xml to 25/10/2021
```
[ ] Yes
[x] No
```
=> Updated CVE suppression dates

Jenkinsfile_CNP, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1736
```
[ ] Yes
[x] No
```
=> Update Jenkinsfile_CNP syncBranchesWithMaster

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Amend suppression date by 1 month
```
[ ] Yes
[X ] No
```
=> Amend suppression date by 1 month

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2590
Suppressing:
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550
```
[ ] Yes
[ x] No
```
=> CCD-2590: Suppress CVE pending investigation

charts/ccd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
=> helm chart update

dependency-check-suppressions.xml
Also added dates if they do not have them
https://tools.hmcts.net/jira/browse/CCD-2497
Amended the CVE suppression date by a month
```
[ ] Yes
[ X] No
```
=> Amend Suppression Dates

build.gradle
https://tools.hmcts.net/jira/browse/CCD-2718
```
[ ] Yes
[ ] No
```
=> update test definition version to 7.13.0

charts/ccd-user-profile-api/Chart.yaml
=> Upgrade to Latest Base Helm Charts

dependency-check-suppressions.xml
=> --Adding the Suppression for Spring Beans jar. Temporary fix.

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2920
```
[ ] Yes
[ ] No
```
=> spring framework version update to 5.3.18

dependency-check-suppressions.xml
There are several dependency check failures, this change is suppressing them.
```
[ ] Yes
[ x] No
```
=> CVE Multiple issues suppressions

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2816
```
[ ] Yes
[ ] No
```
=> jackson.version update for CVE-2020-36518

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3289
```
[ ] Yes
[x] No
```
=> suppression of CVE-2022-22970,CVE-2022-22971

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3289
Removed suppressions and updated spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```
=> Removed suppressions and updated spring-framework.version to 5.3.20

build.gradle
https://tools.hmcts.net/jira/browse/CCD-3297
```
[ ] Yes
[ x] No
```
=> CCD-3297: Added junit formatter to smoke and functional test tasks

charts/ccd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-3376
AKS is failing in Preview Env - update java charts
```
[ ] Yes
[x] No
```
=> CCD-3376 update java chart version

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3387
Remove CVE Suppress Until Date from All Services
```
[ ] Yes
[x ] No
```
=> CCD-3387 Remove CVE Suppress Until Date from All Services

charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```
=> CCD-3434 Upgrade Java, postgresql and redis configurations

build.gradle
https://tools.hmcts.net/jira/browse/CCD-965
CCD-965: Remove Temporary Sonar Exclusions ccd-user-profile-api
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-965: Remove Temporary Sonar Exclusions ccd-user-profile-api

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3515
CVE-2022-22976
```
[ ] Yes
[x ] No
```
=> Ccd 3515 CVE 2022 22976

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[x ] No
```
=> CCD-3577 Cleanup CVE Suppressions 

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
CCD-3672 (https://tools.hmcts.net/jira/browse/CCD-3672)
Updated DEFINITION_STORE_URL_BASE URL value in Jenkinsfile_CNP.  Changed value to use https instead of http.  Also changed value to use definitionStoreDevelopPr property so that it's consistent with other CCD projects.
Updated befta-fw and ccd-test-definition dependencies to fix errors encountered during high level data setup stage of builds.
```
[ ] Yes
[x] No
```
=> CCD-3672: Fix preview deploy issues

build.gradle
https://tools.hmcts.net/jira/browse/CCD-3563
Remove Version Number
```
[ ] Yes
[ X] No
```
=> Remove Version Number

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3658
CCD 3658 suppress CVE CVE 2022 25857 - fix (updated snakeyaml in build.gradle and removed CVEs as needed from suppressions file.
```
[ ] Yes
[X] No
```
=> CCD 3658 suppress CVE CVE 2022 25857 - fix

dependency-check-suppressions.xml
=> Added CVE suppression

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3918
```
[ ] Yes
[ x] No
```
=> CCD-3918 CVE-2022-42252

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3917
Upgrade to Spring Security
- CVE-2022-31690 CVE-2022-31692
```
[ ] Yes
[ x] No
```
=> CCD-3917 Spring Security Upgrade

.github/workflows/dependency-check.yml, build.gradle, dependency-check-suppressions.xml, gradle/suppress.gradle
https://tools.hmcts.net/jira/browse/CCD-3533
Introduce suppressCves Task to suppress CVEs
Cron job to build the pipeline regularly
Clean up dependency-check-suppressions.xml
- Comments are stripped by the cleanSuppressions task which runs after the suppressCVEs task
```
[ ] Yes
[ x] No
```
=> CCD-3533 Add suppressCves task

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4047
Upgraded 'org.postgresql' to version: '42.5.1'
```
[ ] Yes
[X] No
```
=> CCD-4047-Fix-CVE-2022-41946

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4157
Suppress CVEs
```
[ ] Yes
[X] No
```
=> CCD-4157: Suppress CVE

charts/ccd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
=> Ccd 4317 upgrade base charts

.github/workflows/swagger.yml, README.md
https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : replaced reform-api-docs with cnp-api-docs
```
[ ] Yes
[X] No
```
=> CCD-4476 : replaced reform-api-docs with cnp-api-docs

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4479
https://tools.hmcts.net/jira/browse/CCD-4509
Fix for https://github.com/advisories/GHSA-564r-hj7v-mcr5
Fix for https://github.com/advisories/GHSA-7phw-cxx7-q9vq
upgrade Spring Framework version to 5.3.26
```
[ ] Yes
[ ] No
```
=> CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860 

build.gradle
NA
Updated task Functional, added 'dependsOn aatClasses'
```
[ ] Yes
[X] No
```
=> Update build.gradle task Functional

build.gradle
NA
Attempt to fix master build pipeline failure
```
[ ] Yes
[X] No
```
=> Update build.gradle Functional Task

build.gradle
=> added logging

build.gradle
=> revert reporting library to match data store

Jenkinsfile_CNP
=> Archive cucumber error reports

.github/renovate.json, Jenkinsfile_CNP, lib/applicationinsights.json
Sample health calls
```
[ ] Yes
[x] No
```
=> CCD-3710 Update applicationinsights.json/fix build

Jenkinsfile_CNP
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4955
Removed the 'demo' environment from the Jenkinsfile_CNP file to disable synchronisation with the demo branch.
```
[ ] Yes
[X] No
```
=> Disabled demo environment synchronisation within Jenkinsfile_CNP

Jenkinsfile_CNP, dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4955
This PR includes the necessary updates for implementing PostgreSQL version 15. Changes have been made to variables.tf, main.tf, and state.tf to accommodate the new version and its configurations.
```
[ ] Yes
[x] No
```
=> CCD-4955 -- Postgres v15 update to Flex DB

Jenkinsfile_CNP
Added demo environment for branch sync 
```
[ ] Yes
[x] No
```
=> Added demo environment to branchesToSync array

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars
- Add subnet_suffix for expanded subnet in Terraform config
- Added psql_sku's for all environments in tfvars related to flexible server migration.
```
[ ] Yes
[x] No
```
=> Add subnet_suffix for expanded subnet in Terraform config

charts/ccd-user-profile-api/values.aat.template.yaml
Updating references to V15 flexible server 
```
[ ] Yes
[x] No
```
=> Updating to v15 flexible server reference

infrastructure/main.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4990
Adding permissions trigger
```
[ ] Yes
[x] No
```
=> Adding permissions trigger

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5105
https://github.com/jeremylong/DependencyCheck
Change as suggested by plat-ops:
```
[ ] Yes
[x] No
```
=> CCD-5105: dependency check suppressions

acb.tpl.yaml
https://tools.hmcts.net/jira/browse/CCD-5045
=> CCD-5045 : Fix acb entries to fix timeout issue

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5197
Excluded H2 dependency to resolve CVE
```
[ ] Yes
[X] No
```
=> 5197 Excluded H2 transitive dependency to resolve CVE

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5203
Bumped a version of a transitive dependency to resolve a CVE
```
[ ] Yes
[X] No
```
=> Version bumped to resolve CVE

charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/values.yaml
=> autoscaling set to false until CCD-5163 is progressed.

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5198
Raised Spring version to resolve CVE
```
[ ] Yes
[x] No
```
=> CCD-5198 Raised Spring version to resolve CVE

charts/ccd-user-profile-api/Chart.yaml, charts/ccd-user-profile-api/values.yaml
[CCD-5273](https://tools.hmcts.net/jira/browse/CCD-5273)
=> CCD-5273 Update values.yaml point to v15 d/b

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5474
Fix CVE-2023-33202 : Bumped bouncycastle to address cve
```
[ ] Yes
[X] No
```
=> CCD-5474 : Fix CVE-2023-33202 : Bumped bouncycastle to address cve

build.gradle
https://tools.hmcts.net/jira/browse/CCD-5825
Fix for fortify client causing FortifyScan stage to fail
```
[ ] Yes
[X] No
```
=> fix for fortify stage

.github/workflows/dependency-check.yml, .github/workflows/swagger.yml, .travis.yml, Dockerfile, README.md, acb.tpl.yaml, build.gradle, docker/database/Dockerfile, src/integrationTest/java/uk/gov/hmcts/ccd/BaseTest.java, src/integrationTest/resources/application-it.yml
https://tools.hmcts.net/jira/browse/CME-51
Update to Java 21
```
[ ] Yes
[x] No
```
=> CME-51 update to Java 21

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-315
```
[ ] Yes
[x ] No
```
=> CME-315: Update azurerm 

charts/ccd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
=> CCD-6193 update base chart versions

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-482
```
[ ] Yes
[ x] No
```
=> CME-482: Disable sync to ITHC for database monitoring testing

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-482
```
[ ] Yes
[ x] No
```
=> CME-482: Add database monitoring

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6363
https://tools.hmcts.net/jira/browse/CCD-6364
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[X] No
```
=> Suppress CVE-2024-52316 and CVE-2024-52317 
